calaxe/config/routes.rb
XPost::Application.routes.draw do
  root :to => "pages#home"

  namespace :admin do
    root :to => "posts#index"
    resources :posts do
      collection do
        get :overview
        get :imported
      end
    end

    resources :errors, :only => [:index, :show, :edit, :destroy] do
      collection{ post :remove }
    end

    resources :import_settings, :only => [:index]
    resources :settings, :only => [:index, :update]

    match 'login'  => "sessions#new",     :as => :login,  :via => :get
    match 'login'  => "sessions#create",  :as => :login,  :via => :post
    match 'logout' => "sessions#destroy", :as => :logout, :via => :get
  end

  controller "pages",  :path => "/" do
    match 'contact', :action => :contact, :via => :get
    match 'about',   :action => :about,   :via => :get
    match 'privacy', :action => :privacy, :via => :get
    match 'terms',   :action => :terms,   :via => :get
    match 'help',    :action => :help,    :via => :get
  end

  resources :posts do
    member do
      get   :preview
      post  :continue
      match "publish/:security_id", :action => :publish, :via => :get, :as => :publish
      match "delete/:security_id",  :action => :delete,  :via => :get, :as => :delete
    end

    collection do
      get   :add
      match "add/:cat",        :action => :new,    :via => :get
      match "add/:cat(/:sub)", :action => :new,    :via => :get
      match "add/:cat/:sub",   :action => :create, :via => :post

      match "new/:cat",        :action => :new,    :via => :get
      match "new/:cat(/:sub)", :action => :new,    :via => :get, :as => :add
      match "new/:cat/:sub",   :action => :create, :via => :post

      get :instructions
      get :featured
    end

    resources :messages, :only => [:create]
  end

  resources :jobs, :only => [:index] do
    collection do
      get :subscriber
      get :unsubscribe
      get :success
    end
  end

  match "job"            => "jobs#index"
  match "job/subscriber" => "jobs#subscriber"
  match "unsubscribe"    => "jobs#unsubscribe"
  match "success"        => "jobs#success"

end

calaxe/app/models/post.rb
class Post < ActiveRecord::Base
  include ThreetapsIntegration

  # Filters
  before_validation :trim_spaces
  before_validation :assign_timestamp, :on => :create

  # Comment this line when importing data
  before_create :add_extra_information

  after_initialize :init

  # Class variables
  cattr_accessor :last_time

  attr_accessor :from_admin, :timestamp_type

  # Accessor, accessible, reader, writer
  attr_accessible :name, :body,           :email,
                         :category_id,    :subcategory_id, :ip,
                         :time_posted,    :status,
                         :image_source1,  :image_source2,
                         :image_source3,  :image_source4,
                         :image_source1_file_name, :image_source2_file_name,
                         :image_source3_file_name, :image_source4_file_name,
                         :timestamp_type, :featured

  # Associations
  has_many :messages

  def self.per_page
    15
  end

  # Constants
  STATUS_NEW         = -1
  STATUS_UNPUBLISHED = 0
  STATUS_ACTIVE      = 1
  STATUS_DELETED     = 2

  STATUSES = {
    STATUS_NEW         => "New",
    STATUS_UNPUBLISHED => "Unpublished",
    STATUS_ACTIVE      => "Active",
    STATUS_DELETED     => "Deleted"
  }

  NOW              = 0
  ONE_WEEK_RANDOM  = 1
  ONE_MONTH_RANDOM = 2

  TIMESTAMP_TYPES = {
    NOW              => "Now",
    ONE_WEEK_RANDOM  => "One week random interval",
    ONE_MONTH_RANDOM => "One month random with interval"
  }


  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d.\-]+\.[a-z]+\z/i

  DOMAIN = SITE_CONFIG[:allowed_domains].map { |d| '[\w+\-.]+@' + Regexp.quote(d) }.join(')|(')

  WHITE_LIST_EMAILS = SITE_CONFIG[:white_list_emails].map { |e| "(#{Regexp.quote(e)})" }.join("|")

  if SITE_CONFIG[:allowed_subdomain]
    SUBDOMAIN = Array(SITE_CONFIG[:allowed_subdomain]).map do |d|
      '(' + '[\w+\-.]+@([a-z][a-z\d\-]*\.)+' + Regexp.quote(d) + ')'
    end.join('|')
    ACCEPTED_EMAIL_REGEX = /\A(#{DOMAIN})|(#{SUBDOMAIN})|#{WHITE_LIST_EMAILS}\z/i
    VERIFIED_EMAIL_REGEX = /\A(#{DOMAIN})|(#{SUBDOMAIN})\z/i
  else
    ACCEPTED_EMAIL_REGEX = /\A(#{DOMAIN})|#{WHITE_LIST_EMAILS}\z/i
    VERIFIED_EMAIL_REGEX = /\A(#{DOMAIN})\z/i
  end

  STYLES = {
    :post   => "340x700>", # width x height
    :ticker => "x120"
  }

  OPTIONS = {
    :styles         => STYLES,
    :default_url    => "/images/missing.png",
    :storage        => :s3,
    :s3_credentials => "#{Rails.root.to_s}/config/amazon_s3.yml",
    :path           => "posts/:id/:style_:basename.:extension"
  }

  TIME_FORMAT = "%a %b %d, %Y %I:%M %p"

  HAS_PHOTO_QUERY = [1, 2, 3, 4].map{ |i| "(#{self.table_name}.image_source#{i}_file_name IS NOT NULL)" }.join(" OR ")

  # Validations and callbacks
  validates :name, :presence => true, :length => { :maximum =>  71 }, :if => lambda{ |p|  !p.from_admin }
  validates :name, :presence => true, :length => { :maximum => 255 }, :if => lambda{ |p| !!p.from_admin }

  validates :body,
            :presence => true,
            :length   => { :maximum => 32000 }

  validates :email,
            :presence => true,
            :format   => {
              :with        => EMAIL_REGEX,
              :message     => "must be valid",
              :allow_nil   => true,
              :allow_blank => true
            }

  validates :category_id,
            :subcategory_id,
            :presence => true

  # has_attached_file :avatar, options
  has_attached_file :image_source1, OPTIONS
  has_attached_file :image_source2, OPTIONS
  has_attached_file :image_source3, OPTIONS
  has_attached_file :image_source4, OPTIONS

  # Named scope, scope
  # Search for posts with photos.
  scope :has_photo, where(HAS_PHOTO_QUERY)
  scope :active,
        lambda { where("status = ? AND time_posted <= ?", STATUS_ACTIVE, Time.now.to_i) }

  scope :future,
        lambda { where("status = ? AND time_posted > ?", STATUS_ACTIVE, Time.now.to_i) }
  scope :recent, order("time_posted DESC")
  scope :this_week,
        lambda { where("time_posted > ?", (Time.now - 7.days).to_i) }
  scope :category,
        lambda { |category_id| where(:category_id => category_id) }
  scope :subcategory,
        lambda { |subcategory_id| where(:subcategory_id => subcategory_id) }
  scope :query,
        lambda { |query| where("lower(name) LIKE ? OR lower(body) LIKE ?", "%#{query.downcase}%", "%#{query.downcase}%") }

  scope :order_by, lambda { |sort_type| order("time_posted #{sort_type}") }

  scope :imported, where('threetaps_id IS NOT NULL')
  scope :manual,   where('threetaps_id IS NULL')
  scope :featured, lambda{ active.where(:featured => true) }
  scope :normal, where('featured IS NULL OR featured IS FALSE')

  # Instance methods
  def from_craigslist?
    email.present? && email =~ /craigslist\.(com|org)$/
  end

  def product
    case self.category_id
    when CAMPUS_JOBS_CATEGORY_ID
      "campus-job"
    when JOBS_CATEGORY_ID
      "jobs"
    when HOUSING_CATEGORY_ID
      "housing"
    when FOR_SALE_CATEGORY_ID
      self.subcategory_id == CARS_SUBCATEGORY_ID ? "for-sale-cars" : "for-sale-non-cars"
    when SERVICES_CATEGORY_ID
      "services"
    when PERSONALS_CATEGORY_ID
      "personals"
    when COMMUNITY_CATEGORY_ID
      "community"
    else
      "for-sale-non-cars"
    end
  end

  def from_university?
    email =~ ACCEPTED_EMAIL_REGEX
  end

  def mark_as_unpublished
    self.update_attributes(:status => STATUS_UNPUBLISHED)
  end

  def activate
    self.update_attributes(:status => STATUS_ACTIVE) if self.unpublished? || self.deleted?
  end

  def republish
    self.update_attributes(:status => STATUS_ACTIVE)
  end

  def unpublish
    self.update_attributes(:status => STATUS_DELETED) if self.active?
  end

  def deliver_activate_mail
    NotifierMailer.activate(self).deliver
  end

  # Virtual Attributes

  def css
    CATEGORIES[category_id].try(:[], :css)
  end

  def date
    full_time.to_date
  end

  def full_date
    date.strftime("%b %d, %Y")
  end

  def short_date
    date.strftime("%a, %b %d")
  end

  def time
    full_time.strftime(TIME_FORMAT)
  end

  def full_time
    Time.at(time_posted)
  end

  def category
    CATEGORIES[category_id].try(:[], :short_name)
  end

  def subcategory
    SUBCATEGORIES[subcategory_id].try(:[], :name)
  end

  def status_name
    STATUSES[self.status]
  end

  def name_with_tag
    email.match(VERIFIED_EMAIL_REGEX) ? "#{name} #{SITE_CONFIG[:symbol_email]}" : name
  end

  def verified?
    !!email.match(VERIFIED_EMAIL_REGEX)
  end

  # Instance methods
  # Does this post have a photo or not?
  def has_photo?
    image_source1_file_name.present? || image_source2_file_name.present? || image_source3_file_name.present? || image_source4_file_name.present?
  end

  def new?
    status == STATUS_NEW
  end

  # Is this an active post?
  def active?
    status == STATUS_ACTIVE
  end

  def unpublished?
    status.nil? || status == STATUS_UNPUBLISHED
  end

  def deleted?
    status == STATUS_DELETED
  end

  def unavailable?
    new? || deleted? || unpublished?
  end

  def new_day?
    klass = self.class
    if klass.last_time.nil? || klass.last_time != date
      klass.last_time = date
      true
    else # klass.last_time == date # Same date
      false
    end
  end

  # Sample photo -- regardless of the image_source attribute originally
  # assigned by user
  def photo
    return image_source1.url(:ticker) unless image_source1_file_name.blank?
    return image_source2.url(:ticker) unless image_source2_file_name.blank?
    return image_source3.url(:ticker) unless image_source3_file_name.blank?
    return image_source4.url(:ticker) unless image_source4_file_name.blank?
  end

  # Return photos for this post as an array
  def photos
    photos = []
    photos << image_source1.url(:post) unless image_source1_file_name.blank?
    photos << image_source2.url(:post) unless image_source2_file_name.blank?
    photos << image_source3.url(:post) unless image_source3_file_name.blank?
    photos << image_source4.url(:post) unless image_source4_file_name.blank?
    photos
  end

  # Class methods
  def self.subcategories(category_id)
    CATEGORY_SUBCATEGORIES_ARRAY[category_id.to_i] || []
  end

  def self.category_activity_metrics
    activity = {}
    count_by_category = Post.category(CATEGORIES.keys).this_week.group(:category_id).count
    CATEGORIES_ORDER.each do |cid|
      post = Post.category(cid).active.recent.first

      activity[cid] = {
        #:count => category(cid).count_this_week,
        :count => count_by_category[cid] || 0,
        :recent_time => post.full_time
      } if post
    end
    activity
  end

  # Count the posts this week
  def self.count_this_week
    self.this_week.active.count
  end

  def self.verified_posts
    sql    = SITE_CONFIG[:allowed_domains].map{ |_| "email LIKE ?" }.join(' OR ')
    values = SITE_CONFIG[:allowed_domains].map{ |d| "%#{d}" }
    arel   = self.active.recent.normal
    arel   = arel.where([sql, *values])
    arel   = arel.where(["time_posted >= ?", (Time.now - 2.weeks).to_i])
    arel.limit(50)
  end

  # Search for posts based on search criteria specified within params
  def self.posts( params )
    limit = params[:controller] == "posts" ? 100 : 50

    if params[:cat] && params[:cat].to_i == JOBS_CATEGORY_ID
      finder = self.active.recent
    else
      finder = self.active.recent.normal
    end
    finder = finder.category(params[:cat]) unless params[:cat].nil?
    finder = finder.subcategory(params[:sub]) unless params[:sub].nil?
    finder = finder.query( params[:q] ) unless params[:q].nil?
    finder = finder.paginate(:page => params[:page], :per_page => limit)
  end

  # Find the 4 most recent posts with photos
  def self.find_recent_photos
    self.has_photo.recent.active.limit(4)
  end

  # This function is written to import data
  def self.create_with_id(attributes)
    post = Post.new(attributes)
    post.id = attributes[:id]
    post.save!(:validate => false)
  end

  def self.search_by_params(params)

calaxe/app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_filter :login_required
  before_filter :find_post, :only => [:show, :edit, :update]

  def index
    @posts = Post.manual.search_by_params(params)
  end

  def new
    @post = Post.new :status => Post::STATUS_ACTIVE, :timestamp_type => Post::ONE_WEEK_RANDOM
  end

  def create
    @post = Post.new params[:post]
    @post.from_admin = true

    if @post.save
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def show
    render 'edit'
  end

  def edit
  end

  def update
    @post.from_admin = true

    if @post.update_attributes(params[:post])
      redirect_to edit_admin_post_path(@post)
    else
      render @post
    end
  end

  def overview
    @sort_type = params[:sort] || "asc"
    @posts = Post.future.order_by(@sort_type).page(params[:page]).per_page(30).all
    @posts_by_date = @posts.group_by(&:date)
  end

  def imported
    @posts = Post.search_imported_posts(params)
  end

  def verified
  end

  private

    def find_post
      @post = Post.find params[:id]
    end
end

calaxe/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_last_time
  before_filter :find_post,                     :only => [:preview, :continue, :show]
  before_filter :find_secured_post,             :only => [:publish, :delete]
  before_filter :find_category_and_subcategory, :only => [:new, :create]

  def index
    @posts = Post.posts params
    @title = "Posts"
  end

  def new
    @title = "Post"
    @post  = new_post @category, @subcategory
  end

  def create
    @title = "Post"
    @post  = new_post @category, @subcategory

    if @category.present? && @subcategory.present? && @post.save
      update_session_for_post(@post)
      redirect_to preview_post_path(@post)
    else
      render "new"
    end
  end

  def preview
    @title = "Publish your post | #{@post.name}"
  end

  def continue
    redirect_to post_path(@post) and return unless @post.new?
    redirect_to root_path and return unless check_session_for_post?(@post)

    Post.transaction do
      @post.mark_as_unpublished
      unless @post.from_university?
        @post.activate
        expire_home_page
      end
      @post.deliver_activate_mail
    end

    update_session_for_post(nil)
    if @post.from_university?
      redirect_to instructions_posts_path
    else
      redirect_to post_path(@post)
    end
  end

  def show
    redirect_to root_path and return if @post.unavailable?
    @title   = @post.name
    @message = Message.new :message => flash[:message], :email => flash[:email]
  end

  def publish
    @post.republish
    expire_home_page
  end

  def delete
    @post.unpublish
    expire_home_page
  end

  def instructions
  end

  def featured
    @posts = Post.featured.recent.page(params[:page]).per_page(100)
    render "index"
  end

  private

  def update_session_for_post(post)
    session[:post_id]     = post.try(:id)
    session[:security_id] = post.try(:security_id)
  end

  def check_session_for_post?(post)
    return false if post.blank?
    session[:post_id] == post.id && session[:security_id] == post.security_id
  end

  def new_post(category, subcategory)
    Post.new(params[:post]) do |post|
      post.status = Post::STATUS_NEW
      post.ip     = request.remote_ip

      if category.present? && post.category_id.blank?
        post.category_id = category[:id]

        if subcategory.present? && post.subcategory_id.blank?
          post.subcategory_id = subcategory[:id]
        end
      elsif category.blank? && post.category_id.present? && CATEGORIES[post.category_id.to_i]
        category = CATEGORIES[post.category_id.to_i]

        if subcategory.blank? && category.present? && post.subcategory_id.present? && SUBCATEGORIES[post.subcategory_id.to_i]
          subcategory = SUBCATEGORIES[post.subcategory_id.to_i]
        end
      end
    end
  end

  def find_post
    @post = Post.find params[:id]
  end

  def find_secured_post
    @post = Post.find_by_id_and_security_id params[:id], params[:security_id]
  end

  def find_category_and_subcategory
    @category    = nil
    @subcategory = nil

    if params[:cat].present?
      @category = CATEGORIES[params[:cat].to_i]

      if @category.present? && params[:sub].present?
        @subcategory = SUBCATEGORIES[params[:sub].to_i]
      end
    end
  end

  def set_last_time
    Post.last_time = nil
  end
end

calaxe/app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post], :html => { :multipart => true } do |f| %>
  <table class='post-form'>
    <colgroup>
      <col class='label'>
      <col class='value'>
    </colgroup>

    <tr>
      <td><%= f.label :category_id %></td>
      <td><%= f.select :category_id, CATEGORIES.map{ |k, v| [v[:short_name], k] } %></td>
    </tr>

    <tr>
      <td><%= f.label :subcategory_id %></td>
      <td><%= f.select :subcategory_id, [] %></td>
    </tr>

    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name, :maxlength => 254 %></td>
    </tr>

    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email, :maxlength => 254 %></td>
    </tr>

    <tr>
      <td><%= f.label :body %></td>
      <td><%= f.text_area :body %></td>
    </tr>

    <tr>
      <td><%= f.label :status %></td>
      <td><%= f.select :status, Post::STATUSES.map{ |k, v| [v, k] } %></td>
    </tr>

    <tr>
      <td><%= f.label :featured %></td>
      <td><%= f.check_box :featured %></td>
    </tr>

    <% if @post.new_record? %>
      <tr>
        <td><%= f.label :timestamp_posted %></td>
        <td>
          <% Post::TIMESTAMP_TYPES.each do |k, v| %>
            <div>
              <%= f.radio_button :timestamp_type, k %>
              <%= label_tag "post_timestamp_type_#{k}", v %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>

    <% (1..4).each do |idx| %>
      <% field = :"image_source#{idx}" %>
      <tr>
        <td><%= f.label field %></td>
        <td>
          <%= image_tag @post.send(field).url(:post), :class => 'post-image' if @post.persisted? %>
          <%= f.file_field field %>
        </td>
      </tr>
    <% end %>

    <tr>
      <td>&nbsp;</td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end %>

calaxe/app/views/admin/posts/_js_css.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'jquery-ui-timepicker-addon' %>
<% end %>

<%= content_for :js do %>
  <script type="text/javascript">
    CSA = <%= CATEGORY_SUBCATEGORIES_ARRAY.to_json.html_safe %>;
  </script>

  <script id="option-template" type="text/x-jquery-tmpl">
    <option value="${id}">${name}</option>
  </script>

  <%= javascript_include_tag "admin", "jquery-ui-timepicker-addon" %>
<% end %>

calaxe/app/views/admin/posts/_search.html.erb
<%= form_tag url, :method => :get, :id => 'search-form' do %>
  <%= select_tag :field, options_for_select(Post::FIELDS_FOR_SEARCH, :selected => params[:field]) %>
  <%= text_field_tag :query, params[:query], :id => 'search-box' %>
  <%= submit_tag 'Search', :id => 'search-button', :name => nil %>
<% end %>

calaxe/app/views/admin/posts/edit.html.erb
<%= render 'admin/posts/js_css' %>

<div id="main">
  <div class="container">
    <%= render 'shared/error_messages' %>

    <div id="post-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

calaxe/app/views/admin/posts/imported.html.erb
<div id='main'>
  <div class="container">

  <%= render 'search', :url => imported_admin_posts_path %>

  <table class="imported-posts">
    <colgroup>
      <col class="id" />
      <col class='name' />
      <col class='category' />
      <col class='subcategory' />
      <col class='status' />
      <col class='poster' />
      <col class='posted-date' />
      <col class='photo' />
      <col class='3taps-id' />
      <col class='url' />
      <col class='url' />
    </colgroup>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Status</th>
      <th>Poster</th>
      <th>Posted Date</th>
      <th>Photo?</th>
      <th>3taps ID</th>
      <th>Url</th>
      <th>Original Url</th>
    </tr>
    <% @posts.each_with_index do |p, index| %>
      <tr class="row-<%= index % 2 %>">
        <td class='center'><%= p.id %></td>
        <td><%= link_to p.name, edit_admin_post_path(p) %></td>
        <td><%= p.category %></td>
        <td><%= p.subcategory %></td>
        <td class='center'><%= p.status_name %></td>
        <td><%= p.email %></td>
        <td class='center'><%= p.full_date %></td>
        <td class="has-photo-<%= p.has_photo? %>">&nbsp;</td>
        <td class='center'><%= p.threetaps_id %></td>
        <td class='center'><%= link_to 'View', post_path(p),   :target => '_blank' %></td>
        <td class='center'><%= link_to 'View', p.external_url, :target => '_blank' %></td>
      </tr>
    <% end %>

  </table>

  <%= show_pagination(@posts) %>

  </div>
</div>

calaxe/app/views/admin/posts/index.html.erb
<div id='main'>
  <div class="container">

  <%= render 'search', :url => admin_posts_path %>

  <table class="posts">
    <colgroup>
      <col class='id' />
      <col class='name' />
      <col class='category' />
      <col class='subcategory' />
      <col class='status' />
      <col class='poster' />
      <col class='posted-date' />
      <col class='featured' />
      <col class='photo' />
      <col class='url' />
    </colgroup>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Status</th>
      <th>Poster</th>
      <th>Posted Date</th>
      <th>Featured?</th>
      <th>Photo?</th>
      <th>URL</th>
    </tr>
    <% @posts.each_with_index do |p, index| %>
      <tr class="row-<%= index % 2 %>">
        <td><%= p.id %></td>
        <td><%= link_to p.name, edit_admin_post_path(p) %></td>
        <td><%= p.category %></td>
        <td><%= p.subcategory %></td>
        <td class='center'><%= p.status_name %></td>
        <td><%= p.email %></td>
        <td class='center'><%= p.full_date %></td>
        <td class="<%= p.featured? ? 'featured-post' : 'normal-post' %>">&nbsp;</td>
        <td class="has-photo-<%= p.has_photo? %>">&nbsp;</td>
        <td class='center'><%= link_to 'View', post_path(p), :target => '_blank' %></td>
      </tr>
    <% end %>

  </table>

  <%= show_pagination(@posts) %>

  </div>
</div>

<script type='text/javascript'>
  jQuery(document).ready(function () {
    jQuery('#search-form #field').find('option[value=threetaps_id]').remove();
  });
</script>

calaxe/app/views/admin/posts/new.html.erb
<%= render 'admin/posts/js_css' %>

<div id="main">
  <div class="container">
    <%= render 'shared/error_messages' %>

    <div id="post-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

calaxe/app/views/admin/posts/overview.html.erb
<div id='main'>
  <div class="container">
    <div class='clearfix overview-header'>
      <div id="overview" class='left'>
        Total posts will appears in next time:
        <span><%= @posts.total_entries %><span>
      </div>

      <div id='sort' class="right">
        <%= sort_link(@sort_type) %>
      </div>
    </div>

    <table class="posts">
      <colgroup>
        <!--<col class="checkbox" />-->
        <col class='name' />
        <col class='category' />
        <col class='subcategory' />
        <col class='status' />
        <col class='poster' />
        <col class='photo' />
      </colgroup>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Subcategory</th>
        <th>Status</th>
        <th>Poster</th>
        <th>Photo?</th>
      </tr>
      <% @posts_by_date.each do |date, posts| %>
        <tr class="header">
          <td colspan="6">
            <div class='date'>
              <span class='label'>Date:</span>
              <span class="value"><%= date.strftime("%b %d, %Y") %></span>
            </div>
            <div class='total'>
              <span class='label'>Total:</span>
              <span class="value"><%= posts.size %></span>
            </div>
          </td>
        </tr>
        <% posts.each_with_index do |p, index| %>
        <tr class="row-<%= index % 2 %>">
          <td><%= link_to p.name, edit_admin_post_path(p) %></td>
          <td><%= p.category %></td>
          <td><%= p.subcategory %></td>
          <td class='center'><%= p.status_name %></td>
          <td><%= p.email %></td>
          <td class="has-photo-<%= p.has_photo? %>">&nbsp;</td>
        </tr>
        <% end %>
      <% end %>

    </table>

    <%= show_pagination(@posts) %>

  </div>
</div>