calaxe/config/routes.rb
XPost::Application.routes.draw do
  root :to => "pages#home"

  namespace :admin do
    root :to => "posts#index"
    resources :posts do
      collection do
        get :overview
        get :imported
      end
    end

    resources :errors, :only => [:index, :show, :edit, :destroy] do
      collection{ post :remove }
    end

    resources :import_settings, :only => [:index]
    resources :settings, :only => [:index, :update]

    match 'login'  => "sessions#new",     :as => :login,  :via => :get
    match 'login'  => "sessions#create",  :as => :login,  :via => :post
    match 'logout' => "sessions#destroy", :as => :logout, :via => :get
  end

  controller "pages",  :path => "/" do
    match 'contact', :action => :contact, :via => :get
    match 'about',   :action => :about,   :via => :get
    match 'privacy', :action => :privacy, :via => :get
    match 'terms',   :action => :terms,   :via => :get
    match 'help',    :action => :help,    :via => :get
  end

  resources :posts do
    member do
      get   :preview
      post  :continue
      match "publish/:security_id", :action => :publish, :via => :get, :as => :publish
      match "delete/:security_id",  :action => :delete,  :via => :get, :as => :delete
    end

    collection do
      get   :add
      match "add/:cat",        :action => :new,    :via => :get
      match "add/:cat(/:sub)", :action => :new,    :via => :get
      match "add/:cat/:sub",   :action => :create, :via => :post

      match "new/:cat",        :action => :new,    :via => :get
      match "new/:cat(/:sub)", :action => :new,    :via => :get, :as => :add
      match "new/:cat/:sub",   :action => :create, :via => :post

      get :instructions
      get :featured
    end

    resources :messages, :only => [:create]
  end

  resources :jobs, :only => [:index] do
    collection do
      get :subscriber
      get :unsubscribe
      get :success
    end
  end

  match "job"            => "jobs#index"
  match "job/subscriber" => "jobs#subscriber"
  match "unsubscribe"    => "jobs#unsubscribe"
  match "success"        => "jobs#success"

end

calaxe/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :redirect_to_new_job_page

  def index
  end

  def subscriber
  end

  def unsubscribe
  end

  def success
  end

  private

    def redirect_to_new_job_page
      redirect_to SITE_CONFIG[:job_url] and return
    end
end

calaxe/app/views/jobs/_cancel_form.html.erb
<%= render 'wufoo_form' %>

<script type="text/javascript">
  var w7p6s9 = new WufooForm();
  w7p6s9.initialize(<%= SITE_CONFIG[:cancel_form].to_json.html_safe %>);
  w7p6s9.display();
</script>

calaxe/app/views/jobs/_job_post_form.html.erb
<%= render 'wufoo_form' %>

<script type="text/javascript">
  var s7p7p9 = new WufooForm();
  s7p7p9.initialize(<%= SITE_CONFIG[:job_post_form].to_json.html_safe %>);
  s7p7p9.display();
</script>

calaxe/app/views/jobs/_subscriber_form.html.erb
<%= render 'wufoo_form' %>
<script type="text/javascript">
  var w7p6r7 = new WufooForm();
  w7p6r7.initialize(<%= SITE_CONFIG[:subscriber_form].to_json.html_safe %>);
  w7p6r7.display();
</script>

calaxe/app/views/jobs/_wufoo_form.html.erb
<script type="text/javascript">
  var host = (("https:" == document.location.protocol) ? "https://secure." : "http://");
  document.write(unescape("%3Cscript src='" + host + "wufoo.com/scripts/embed/form.js' type='text/javascript'%3E%3C/script%3E"));
</script>

calaxe/app/views/jobs/index.html.erb
<div id="jobs">
  <!-- Header -->
  <div class="job_header">
    <div class="job_title">Post Your Jobs for <%= SITE_CONFIG[:university] %> Students</div>

    <div class="job_phone_and_email">
      <div class="phone">Questions: 1.888.372.8478</div>
      <div class="contact_email">
        <%= mail_to SITE_CONFIG[:contact_email], SITE_CONFIG[:contact_email], :subject => SITE_CONFIG[:site_name] %>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="job_photo">
      <%= image_tag "job_header.jpg" %>
    </div>
  </div><!-- End of Header -->

  <div class="clearfix"></div>

  <!-- Job middle section -->
  <div class="job_middle">
    <div class="left_information">
      <!-- Wufoo Form -->
      <div class="wufoo_form">
        <%= render 'job_post_form' %>
      </div><!-- End of Wufoo Form -->


    </div><!-- End of Left information -->

    <!-- Right information -->
    <div class="right_information">
      <!-- Subscriber -->
      <div class="subscriber">
        <%= link_to "Already subscribed?", subscriber_jobs_path %>
      </div>

      <!-- Why post job -->
      <div class="why_job_post">
        <div class='header_line'>
          Why Post Your Job on <%= SITE_CONFIG[:site_name] %>?
        </div>
        <div class='job_post_point'>
          <%= SITE_CONFIG[:site_name] %> is a classifieds marketplace for <%= SITE_CONFIG[:university] %> students. <%= SITE_CONFIG[:university] %> students visit <%= SITE_CONFIG[:site_name] %> everyday to buy and sell stuff, e.g., bikes, books, cars.
        </div>
        <div class='job_post_point'>
          <%= SITE_CONFIG[:site_name] %> provides access to <%= SITE_CONFIG[:university] %> students and increases the visibility of your job openings. <%= SITE_CONFIG[:university] %> ranks as a world-class educational institution. These talented <%= SITE_CONFIG[:university] %> students want to know about your job opportunities!
        </div>
        <div class='job_post_point'>
          Sign up to post three jobs per month for a subscription of $299 per month.
        </div>

      </div>

      <!-- Video student -->
    </div><!-- End of Right Information -->

  </div><!-- End of Job middel section -->

  <div class="clearfix"></div>
</div>

calaxe/app/views/jobs/subscriber.html.erb
<div id="subscriber">
  <div class="unsubscribe">
    <%= link_to "Unsubscribe?", unsubscribe_jobs_path %>
  </div>

  <!-- Wufoo Form -->
  <div class="wufoo_form">
    <%= render 'subscriber_form' %>
  </div>
</div>

calaxe/app/views/jobs/success.html.erb
<div id="job_success">
  <h1>Thank you</h1>

  <p>
    Your job post will be published on <%= SITE_CONFIG[:site_name] %> within 24 hours.
  </p>
  <p>
    You will receive an email receipt and instructions on how to make additional job posts.
  </p>
  <div>
    <%= link_to "Return to #{SITE_CONFIG[:site_name]}", root_path %>
  </div>

</div>

calaxe/app/views/jobs/unsubscribe.html.erb
<div id="unsubscribe">

  <div class="wufoo_form">
    <%= render 'cancel_form' %>
  </div>
</div>