calaxe/config/routes.rb
XPost::Application.routes.draw do
  root :to => "pages#home"

  namespace :admin do
    root :to => "posts#index"
    resources :posts do
      collection do
        get :overview
        get :imported
      end
    end

    resources :errors, :only => [:index, :show, :edit, :destroy] do
      collection{ post :remove }
    end

    resources :import_settings, :only => [:index]
    resources :settings, :only => [:index, :update]

    match 'login'  => "sessions#new",     :as => :login,  :via => :get
    match 'login'  => "sessions#create",  :as => :login,  :via => :post
    match 'logout' => "sessions#destroy", :as => :logout, :via => :get
  end

  controller "pages",  :path => "/" do
    match 'contact', :action => :contact, :via => :get
    match 'about',   :action => :about,   :via => :get
    match 'privacy', :action => :privacy, :via => :get
    match 'terms',   :action => :terms,   :via => :get
    match 'help',    :action => :help,    :via => :get
  end

  resources :posts do
    member do
      get   :preview
      post  :continue
      match "publish/:security_id", :action => :publish, :via => :get, :as => :publish
      match "delete/:security_id",  :action => :delete,  :via => :get, :as => :delete
    end

    collection do
      get   :add
      match "add/:cat",        :action => :new,    :via => :get
      match "add/:cat(/:sub)", :action => :new,    :via => :get
      match "add/:cat/:sub",   :action => :create, :via => :post

      match "new/:cat",        :action => :new,    :via => :get
      match "new/:cat(/:sub)", :action => :new,    :via => :get, :as => :add
      match "new/:cat/:sub",   :action => :create, :via => :post

      get :instructions
      get :featured
    end

    resources :messages, :only => [:create]
  end

  resources :jobs, :only => [:index] do
    collection do
      get :subscriber
      get :unsubscribe
      get :success
    end
  end

  match "job"            => "jobs#index"
  match "job/subscriber" => "jobs#subscriber"
  match "unsubscribe"    => "jobs#unsubscribe"
  match "success"        => "jobs#success"

end

calaxe/app/views/layouts/_admin_footer.html.erb
<div id="footer" class='prepend-top append-bottom'>
</div>

calaxe/app/views/layouts/_admin_header.html.erb
<div id="header">
  <div class="container">
    <div class="left">
      <%= link_to logo, root_path, :class => :logo %>
    </div>
    <div class="right">
      <div id="submenu">
        <span class="link"><%= current_user.email %></span>
        <%= link_to "Logout", admin_logout_path, :class => :link %>
      </div>
    </div>
  </div>
</div>

calaxe/app/views/layouts/_admin_menu.html.erb
<%
  action = params[:action].to_sym
  action = :new  if action == :create
  action = :edit if action == :update || action == :show
  kontroller = params[:controller]
  menu = ActiveSupport::OrderedHash.new
  menu[:overview]        = { :name => "Overview", :link => overview_admin_posts_path }
  menu[:imported]        = { :name => "Imported Posts", :link => imported_admin_posts_path }
  menu[:index]           = { :name => "Manual Posts", :link => admin_posts_path }
  menu[:new]             = { :name => "New Post", :link => new_admin_post_path }
  menu[:edit]            = { :name => "Edit Post", :link => edit_admin_post_path(@post) } if kontroller == 'admin/posts' && action == :edit
  menu[:import_settings] = { :name => "Import Settings", :link => admin_import_settings_path }
  menu[:settings]        = { :name => "Settings", :link => admin_settings_path }
  menu[:errors]          = { :name => "Errors", :link => admin_errors_path }

  if kontroller == 'admin/errors'
    key = :errors
  elsif kontroller == 'admin/import_settings'
    key = :import_settings
  elsif kontroller == 'admin/settings'
    key = :settings
  else
    key = action
  end
  menu[key].merge! :css => :selected
%>

<div id="menu" class="append-bottom">
  <div class="container">
    <% menu.each do |k, v| %>
    <div class="left">
      <%= link_to v[:name], v[:link], :class => "link #{v[:css]}" %>
    </div>
    <% end %>
  </div>
</div>

calaxe/app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
      <li><%= buy_job_post_link "buy job post" %></li>
			<li><%= link_to "about", about_path %></li>
			<li><%= link_to "contact", contact_path %></li>
			<li><%= link_to "privacy", privacy_path %></li>
			<li><%= link_to "terms", terms_path %></li>
			<li><%= link_to "help", help_path %></li>
		</ul>
	</nav>
	<p>a Greg Wientjes production</p>
	<p><%= SITE_CONFIG[:site_name] %> is not sponsored by, endorsed by, or affiliated with <%= SITE_CONFIG[:university] %>.</p>
	<p><%= SITE_CONFIG[:site_name] %> &copy; 2014</p>
</footer>

calaxe/app/views/layouts/_google_ad_manager.html.erb
k<!-- Google Ad Manager  -->
<script type='text/javascript' src='http://partner.googleadservices.com/gampad/google_service.js'>
</script>
<script type='text/javascript'>
  GS_googleAddAdSenseService("ca-pub-5913108846433714");
</script>
<script type='text/javascript'>
  GS_googleEnableAllServices();
</script>
<script type='text/javascript'>
  GA_googleAddSlot("ca-pub-5913108846433714", "supost_home_300x250");
</script>
<script type='text/javascript'>
  GA_googleFetchAds();
</script>
<!-- Google Ad Manager  -->

calaxe/app/views/layouts/_googleanalytics.html.erb
<%=raw SITE_CONFIG[:google_analytics] %>

calaxe/app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

calaxe/app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><%= SITE_CONFIG[:site_name] %>: Administrator</title>
  <%= csrf_meta_tag %>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'blueprint/ie' %>
  <![endif]-->
  <%= stylesheet_link_tag :jquery %>
  <%= stylesheet_link_tag 'admin' %>

  <%= yield :css %>

  <%= javascript_include_tag :jquery %>
</head>
<body>
  <%= render 'layouts/admin_header' %>
  <%= render 'layouts/admin_menu' %>
  <%= yield :menu %>
  <%= yield %>
  <%= render 'layouts/admin_footer' %>
  <%= yield :js %>
</body>
</html>

calaxe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= favicon_link_tag %>
    <%= render 'layouts/stylesheets' %>
    <%# render 'layouts/google_ad_manager' %>
    <%= render 'layouts/googleanalytics' %>
  </head>

  <body>
    <% if Rails.env.staging? %>
      <div class='container staging-warning'>
        This is a testing website. Please visit the main website to use all features correctly.<br>
        Simply remove the subdomain "staging." from the URL to visit the main site or
        please click <%= link_to 'here', SITE_CONFIG[:site_url] %>
      </div>
    <% end %>

    <div class="container">
      <%= render 'layouts/header/header' %>

      <section class="round">
        <%= yield %>
      </section>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %><br /><br />
      <%= debug(session) if Rails.env.development? %>
    </div>
  </body>
</html>