calaxe/config/routes.rb
XPost::Application.routes.draw do
  root :to => "pages#home"

  namespace :admin do
    root :to => "posts#index"
    resources :posts do
      collection do
        get :overview
        get :imported
      end
    end

    resources :errors, :only => [:index, :show, :edit, :destroy] do
      collection{ post :remove }
    end

    resources :import_settings, :only => [:index]
    resources :settings, :only => [:index, :update]

    match 'login'  => "sessions#new",     :as => :login,  :via => :get
    match 'login'  => "sessions#create",  :as => :login,  :via => :post
    match 'logout' => "sessions#destroy", :as => :logout, :via => :get
  end

  controller "pages",  :path => "/" do
    match 'contact', :action => :contact, :via => :get
    match 'about',   :action => :about,   :via => :get
    match 'privacy', :action => :privacy, :via => :get
    match 'terms',   :action => :terms,   :via => :get
    match 'help',    :action => :help,    :via => :get
  end

  resources :posts do
    member do
      get   :preview
      post  :continue
      match "publish/:security_id", :action => :publish, :via => :get, :as => :publish
      match "delete/:security_id",  :action => :delete,  :via => :get, :as => :delete
    end

    collection do
      get   :add
      match "add/:cat",        :action => :new,    :via => :get
      match "add/:cat(/:sub)", :action => :new,    :via => :get
      match "add/:cat/:sub",   :action => :create, :via => :post

      match "new/:cat",        :action => :new,    :via => :get
      match "new/:cat(/:sub)", :action => :new,    :via => :get, :as => :add
      match "new/:cat/:sub",   :action => :create, :via => :post

      get :instructions
      get :featured
    end

    resources :messages, :only => [:create]
  end

  resources :jobs, :only => [:index] do
    collection do
      get :subscriber
      get :unsubscribe
      get :success
    end
  end

  match "job"            => "jobs#index"
  match "job/subscriber" => "jobs#subscriber"
  match "unsubscribe"    => "jobs#unsubscribe"
  match "success"        => "jobs#success"

end

calaxe/app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> 
        prohibited this post from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

calaxe/app/views/shared/_google_ad_manager.html.erb
<!-- Google Ad Manager -->
<!-- ca-pub-5913108846433714/supost_home_300x250 -->
<script type='text/javascript'>
  GA_googleFillSlot("supost_home_300x250");
</script>
<!-- Google Ad Manager -->

calaxe/app/views/shared/_navigate.html.erb
<div class="post_links">
	<%= link_to "post to classifieds", new_post_path %>
	<p><%= SITE_CONFIG[:symbol_email] %> free</p>
	<%= buy_job_post_link %>
</div>
<div class='count'>
  <span><%= link_to @count_this_week || "", posts_path  %></span> posts this week
</div>
<%= render "shared/navigation/overview",
           :category_activity => @category_activity %>
<%= render "shared/navigation/categories",
           :category_activity => @category_activity %>